name: 🍎 MacOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          cd example
          cmake -B build
          cmake --build build
