name: Update README on Discussion Events

on:
  discussion:
    types: [created, edited]
  discussion_comment:
    types: [created, edited]
  push:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      discussions: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Authenticate with GCP (Service Account Key)
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > /tmp/gcp-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp-key.json"

      - name: Install Dependencies
        run: |
          pip install -r .github/scripts/requirements.txt

      - name: Update README images
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          python .github/scripts/update_readme.py
