name: 🪟 Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name: 🪟 Windows
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: |
          cd example
          cmake -B build -DCMAKE_CXX_FLAGS="/WX"
          cmake --build build
